# Defines our Vagrant environment
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

image = "debian/buster64"

Vagrant.configure("2") do |config|
  config.vm.box = 'generic/alpine319'
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network "forwarded_port", guest: 8080, host: 3000
  config.vm.network "forwarded_port", guest: 80, host: 3001
  config.vm.network "forwarded_port", guest: 8082, host: 3002
end
