name: "admin:deploy:chromatic"
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    name: Chromatic - Admin
    runs-on: ubuntu-latest
    env:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN_ADMIN }}
    steps:
      - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.7
        with:
          fetch-depth: 0
      - uses: actions/setup-node@aca7b64a59c0063db8564e0ffdadd3887f1cbae5 # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Admin | Build
        run: npm install && npm run chromatic -- --exit-zero-on-changes
        working-directory: ./admin
